First, get the HTML files using wget â€“ you'll need to retype the code below because it doesn't cut-and-paste well. These are key because they aren't included in the downloads, which are more reliable for individual details. But there are duplicates in that file and and in the one resulting from this process. They need to be double checked against totals from Lobby overview reults, and against actual filings. The beginning and final page numbers should be increased periodically to capture the newest filings and eliminate filings from past years

    for I in {5756..6660}; do
    wget -Oevents/$I.html "https://www.cfis.state.nm.us/media/ReportLobbyistEvents.aspx?id=$I&el=0"
    done

In [20]:
cd ..

/Users/sandrafish/lobby

In [21]:
cd events

/Users/sandrafish/lobby/events

In [22]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from bs4 import BeautifulSoup
import urllib2
import csv

#the second number must be one above the last file number
for i in xrange(22, 6610):
    try:
        page = urllib2.urlopen('file:{}.html'.format(i))
    except:
        continue
    else:
        soup = BeautifulSoup(page.read())
        #get the name
        n = soup.find(id='ctl00_ContentPlaceHolder1_lblName')
        name = n.string
        print name
#get the table with the data
        table = soup.find('table', 'reportTbl')
        #get the rows
        for row in table.findAll('tr')[2:]:
            col = row.findAll('td')
            eventdate = col[0].string
            eventtype = col[1].string
            recipient = col[2].string
            total = col[3].text.strip()
            record = (i, name, eventdate, eventtype, recipient, total)
            #write to file
            writer = csv.writer(open('events.csv', 'ab'))
            writer.writerow(record)

Melendres, Arthur
Marquez, Charlie
Melendres, Arthur
Barrett, John
Barton, Yvonne
Gutierrez, Paul
Fleisher, Mark
Richmond , Zoe
O'neill, James
Koob, Julianna
Thompson, R.E.
Groenewold, Keven
Idsinga, Beverly
Horan, Lawrence
Huertaz, Terry
Duran, Adela
Ray , Sam
Montoya, Vincent
Minzner, Richard
Menapace, Joseph
Menapace, Joseph
Christensen-Boner, Barbara
Mallery, Peter
Ocheskey, Fred
Phillips, Sonia
Propes, Margaret
Santillanes, Matejka
Rivera-Wiest, Roxanne
Underwood, H. John
Vargas , Vincente
Yamada, Sayuri
Christensen-Boner, Barbara
Duran, Adela
Ferrell, Charles
Johnson, Matthew
McBride, Robert
Montoya, Vincent
Moore, Brent
Ning, Natasha
Scanland, Scott
Smith, William
Thompson, John
Alarid, Vanessa
Alarid, Vanessa
Alarid, Vanessa
Phipps, Candice
Trujillo, Anthony (T.J.)
Pacheco, Jerry
Nation, Brenda
Laca, Gaspar
Phillips, Sonia
Horan, Thomas
Horan, Thomas
Gillis, John
Reilly-Mica, Tara
King, Nancy M.
Bowen, Michael
Sellers, Thomas
Barton, Yvonne
Duran, Adela
Lejuste, Margaret
Scanland, Scott
Puelle, Michael
Cravens, Kent
Horan, Lawrence
Mallery, Peter
Menapace, Joseph
Menapace, Joseph
Trujillo, Antonio
Shoats, Marlene (Marla)
Weaks , Dan
Winn, Lisa
Ray , Sam
Cravens, Kent
Cravens, Kent
Smart, Scott
Henson, Charles
Rel, Ricardo
Rel, Ricardo
Trujillo, Ty
Hoffman, Sarah
Buffett, Sandy
Bowen, Michael
Foster, Karin
Phillips, Sonia
Thompson, John
Ocheskey, Fred
Ocheskey, Fred
Ocheskey, Fred
Ocheskey, Fred
Idsinga, Beverly
Scanland, Scott
Gillis, John
Gillis, John
Underwood, H. John
Moore, Brent
King, Nancy M.
Barrett, John
McGonagle, Minda
Marquez, Charlie
Bowen, Michael
Puelle, Michael
Traynor, Randy
Smith, Allison
Laca, Gaspar
Horan, Lawrence
Minzner, Richard
Horan, Lawrence
Trujillo, Antonio
Romero, Richard
Romero, Richard
Griffith, Sue
Mcclure, Beverlee
Edwards, H. Reese
Gonzales, Ricardo
Vargas , Vincente
Mallery, Peter
Propes, Margaret
Johnson, Matthew
Setter, Drew
Ray , Sam
Duran, Adela
Bullington, James
Santillanes, Matejka
Duran, Adela
Pearce , Amber
Otero, Luke
Cravens, Kent
Trujillo, Anthony (T.J.)
Marquez, Charlie
Foster, Karin
Koob, Julianna
Smart, Scott
Minzner, Richard
Kimble, David
Thompson, John
Gillis, John
Christopher, John
Laubacher, Cynthia
Seligman, Deborah
Moore, Brent
Underwood, H. John
Griffith, Sue
Scanland, Scott
Marquez, Charlie
Groenewold, Keven
Duran, Adela
Bundy, Carter
Rosen, Joshua
Rel, Ricardo
Vargas , Vincente
McGonagle, Minda
Ray , Sam
Mitchell, Rhonda
Setter, Drew
Cravens, Kent
Cravens, Kent
Cravens, Kent
Menapace, Carrie Robin
Trujillo, Anthony (T.J.)
Trujillo, Antonio
Alarid, Vanessa
Alarid, Vanessa
Alarid, Vanessa
Henson, Charles
Melendres, Arthur
Rel, Ricardo
Thompson, John
Thompson, John
Christopher, John
Walker , Jerry
Armenta, Loretta
Loubet, Susan
Turbett, Thom
D'Antonio , Michael
Thompson, John
Thompson, John
Hoffman, Sarah
Bowen, Michael
Henke, Steven
Baca, Ruben
Baca, Ray
Park, Alfred
White, Darren
Chavez, Morris
Walker , Jerry
Trujillo, Ty
Baca, Ray
Duran, Mark
Laubacher, Cynthia
Torza, Deborah
Horan, Lawrence
Archuleta, Floyd
Rosen, Joshua
Trujillo, Anthony (T.J.)
Bowen, Michael
Miller, Michael
Trujillo, Anthony (T.J.)
Seligman, Deborah
Vargas , Vincente
Rel, Ricardo
Reilly-Mica, Tara
King, Nancy M.
Moore, Brent
Gillis, John
Thompson, John
Johnson, Matthew
Laca, Gaspar
Ocheskey, Fred
Ocheskey, Fred
Ocheskey, Fred
Scanland, Scott
Ocheskey, Fred
Brandt, Varney
Horan, Lawrence
Puelle, Michael
Romero, Richard
Griffith, Sue
Griffith, Sue
Minzner, Richard
Menapace, Joseph
Mallery, Peter
Doggett, Elizabeth
Kimble, David
Trujillo, Antonio
Idsinga, Beverly
Otero, Luke
Traynor, Randy
Winn, Lisa
Trujillo, Anthony (T.J.)
Lopez, Daniel
Idsinga, Beverly
Lopez, Daniel
Lopez, Daniel
Setter, Drew
Marquez, Charlie
Cravens, Kent
Bundy, Carter
Alarid, Vanessa
Groenewold, Keven
Cravens, Kent
Cravens, Kent
Groenewold, Keven
Koob, Julianna
Groenewold, Keven
Groenewold, Keven
Santillanes, Matejka
Thompson, R.E.
Seligman, Deborah
Idsinga, Beverly
Gillis, John
Laca, Gaspar
Kimble, David
Kimble, David
King, Nancy M.
Scanland, Scott
Balok, Aron
Romero, Richard
Vargas , Vincente
Ocheskey, Fred
Puelle, Michael
Brandt, Varney
Ray , Sam
Ray , Sam
Laubacher, Cynthia
Duran, Adela
Menapace, Carrie Robin
Rel, Ricardo
Rel, Ricardo
Cravens, Kent
Marquez, Charlie
Bowen, Michael
Trujillo, Anthony (T.J.)
Weaks, Jason
Trujillo, Antonio
Trujillo, Antonio
Thompson, John
Thompson, John
Marquez, Charlie
Marquez, Charlie
Vargas , Vincente
Melendres, Arthur
Hoffman, Sarah
Loubet, Susan
Loubet, Susan
Henson, Charles
Hendry, Jon
Rel, Ricardo
Trujillo, Ty
Rel, Ricardo
Christopher, John
Horan, Thomas
Horan, Thomas
Laubacher, Cynthia
Shoats, Marlene (Marla)
Bowen, Michael
Cravens, Kent
Fulginiti, William
Edwards, H. Reese
Seligman, Deborah
Horan, Thomas
Horan, Thomas
Mallery, Peter
Thompson, John
Donaldson, Robert
Mahr, Edwin
Mahr, Edwin
Mahr, Edwin
Mahr, Edwin
Mahr, Edwin
Mahr, Edwin
Scanland, Scott
Ocheskey, Fred
Ocheskey, Fred
Ocheskey, Fred
Trujillo, Antonio
Vargas , Vincente
Rel, Ricardo
Puelle, Michael
Menapace, Carrie Robin
Gillis, John
Traynor, Randy
Groenewold, Keven
Alarid, Vanessa
Frye, Jamie
Weaks, Jason
King, Nancy M.
Underwood, H. John
Drangmeister, Walter
Smith, Allison
Duran, Adela
Lopez, Daniel
Bundy, Carter
Koob, Julianna
Cravens, Kent
Brandt, Varney
Marquez, Charlie
Trujillo, Anthony (T.J.)
Abeita Torres, Deborah
Idsinga, Beverly
Otero, Luke
Fulginiti, William
Marquez, Charlie
Rutherford, Jeremy
Ray , Sam
Santillanes, Matejka
Fletcher, Shelby
Thompson, John
Seligman, Deborah
King, Nancy M.
McGonagle, Minda
Ocheskey, Fred
Groenewold, Keven
Scanland, Scott
Puelle, Michael
Rakes, Daniel
Rel, Ricardo
Trujillo, Antonio
Duran, Adela
Vargas , Vincente
Harden, Clinton
Bowen, Michael
Marquez, Charlie
Fletcher, Shelby
Fletcher, Shelby
Gonzales, Ricardo
Lopez, Daniel
Santillanes, Matejka
Brandt, Varney
Trujillo, Anthony (T.J.)
Menapace, Carrie Robin
West, Cynthia
Christopher, John
Traynor, Randy
Cravens, Kent
Rel, Ricardo
Trujillo, Ty
Rosen, Joshua
Bowen, Michael
Rosen, Joshua
Rosen, Joshua
Maes, Paula
Loubet, Susan
Henke, Steven
Alarid, Vanessa
Seligman, Deborah
King, Nancy M.
Moore, Brent
Trujillo, Anthony (T.J.)
Cravens, Kent
Moore, Brent
Freeman, Katherine
Chase , Claire
Bowen, Michael
Mallery, Peter
King, Nancy M.
Moore, Brent
Underwood, H. John
Harden, Clinton
Reilly-Mica, Tara
Trujillo, Antonio
Groenewold, Keven
Thompson, Jason
Vargas , Vincente
Rel, Ricardo
Scanland, Scott
Mcclure, Beverlee
Kimble, David
Espinoza, Jason
Thompson, John
Horan, Thomas
Thompson, Jr. , John
Seligman, Deborah
Seligman, Deborah
Puelle, Michael
Cravens, Kent
Brandt, Varney
Trujillo, Anthony (T.J.)
Traynor, Randy
Menapace, Joseph
Walker , Jerry
Vargas , Vincente
Donaldson, Robert
Gonzales, Ricardo
Rutherford, Jeremy
Marquez, Charlie
Marquez, Charlie
Idsinga, Beverly
Fulginiti, William
McGonagle, Minda
McGonagle, Minda
Fleisher, Mark
D'Antonio , Michael
Minzner, Richard
Otero, Luke
Santillanes, Matejka
Ray , Sam
Ray , Sam
Fletcher, Shelby
Fletcher, Shelby
Winn, Lisa
Traynor, Randy
Seligman, Deborah
Scanland, Scott
Romero, Richard
Thompson, R.E.
King, Nancy M.
Maestas-Traynor, Debbie
Otero, Luke
Horan, Lawrence
Vargas , Vincente
Dudley Chavez, Claire
Rel, Ricardo
Idsinga, Beverly
Duran, Adela
D'Antonio , Michael
Santillanes, Matejka
Ray , Sam
Snyder , H. Diane
Trujillo, Ty
Gonzales, Ricardo
Trujillo, Antonio
Traynor, Randy
Alarid, Vanessa
Baca, Terri Nikole
Baca, Terri Nikole
Baca, Terri Nikole
Trujillo, Anthony (T.J.)
Cravens, Kent
Jones, La Vanda
Christopher, John
Traynor, Randy
Thompson, Jr. , John
Ning, Natasha
Rel, Ricardo
Traynor, Randy
Traynor, Randy
Loubet, Susan
Bowen, Michael
Traynor, Randy
Trujillo, Ty
Dye, Jeff
Dye, Jeff
Shoats, Marlene (Marla)
Duran, Mark
Setter, Drew
Rosen, Joshua
Duran, Mark
Baca, Terri Nikole
Alarid, Vanessa
Mallery, Peter
Mallery, Peter
Baca, Ruben
Thompson, John
Thompson, John
Thompson, Jason
Najjar, Daniel
Idsinga, Beverly
Idsinga, Beverly
Idsinga, Beverly
Idsinga, Beverly
Jones, La Vanda
Jones, La Vanda
Seligman, Deborah
Seligman, Deborah
Underwood, H. John
Moore, Brent
King, Nancy M.
Harden, Clinton
Minzner, Richard
Zanios, James
Duran, Adela
Rel, Ricardo
Puelle, Michael
Marquez, Charlie
Fleisher, Mark
Scanland, Scott
Bundy, Carter
Smith, Allison
Seligman, Deborah
Menapace, Joseph
Drake, Tom
D'Antonio , Michael
Horan, Lawrence
Horan, Lawrence
Horan, Lawrence
Donaldson, Robert
Rel, Ricardo
Vargas , Vincente
Ray , Sam
Ray , Sam
Gonzales, Ricardo
Santillanes, Matejka
Trujillo, Antonio
Duran, Mark
Riley , Zachary
Trujillo, Anthony (T.J.)
Horan, Thomas
Martinez, Katherine
Wight, Carol
Idsinga, Beverly
Kopelman, Steve
Traynor, Randy
Maestas-Traynor, Debbie
Walker , Jerry
Walker , Jerry
Harden, Clinton
Leach, Carol
Leach, Carol
Romero, Richard
Sellers, Thomas
Badal, John
Badal, John
Fleisher, Mark
Varela, Eugene
Varela, Eugene
Duran, Adela
Ray , Sam
D'Antonio , Michael
Scanland, Scott
Rutherford, Jeremy
Vargas , Vincente
Snyder , H. Diane
Scanland, Scott
Marquez, Charlie
Weaks , Dan
Rel, Ricardo
Riley , Zachary
Otero, Luke
Otero, Luke
Trujillo, Anthony (T.J.)
Puelle, Michael
Horan, Lawrence
Horan, Lawrence
Martinez, Katherine
Baca, Terri Nikole
Baca, Terri Nikole
Baca, Terri Nikole
Scanland, Scott
Seligman, Deborah
Tonjes, Gary
Idsinga, Beverly
King, Nancy M.
Seligman, Deborah
Laubacher, Cynthia
Leach, Carol
Scanland, Scott
Sanchez, Allen
Groenewold, Keven
Groenewold, Keven
Romero, Richard
Ray , Sam
Ray , Sam
Ocheskey, Fred
D'Antonio , Michael
Otero, Luke
Rosen, Joshua
Gonzales, Ricardo
Chino, Conroy
Marquez, Charlie
Walker , Jerry
Killen, Patrick
Christopher, John
Ning, Natasha
Jones, La Vanda
D'Antonio , Michael
D'Antonio , Michael
Walker , Jerry
Bowen, Michael
Moore, Brian
Ning, Natasha
Duran, Mark
Young, Tasia
Duran, Mark
Thompson, Jr. , John
Martinez, Katherine
Balzano, Cristoforo
Balzano, Cristoforo
Thompson, Jason
Scanland, Scott
Cadena, Denicia
Baca, Terri Nikole
D'Antonio , Michael
Rel, Ricardo
Ray , Sam
Najjar, Daniel
Romero, Robert
King, Nancy M.
Moore, Brent
Puelle, Michael
Donaldson, Robert
Otero, Luke
Lloyd, Robin
Baca, Terri Nikole
Marquez, Charlie
Templeman, William
Duran, Adela
Groenewold, Keven
Mallery, Peter
Horan, Lawrence
Fleisher, Mark
Traynor, Randy
Trujillo, Antonio
Jaramillo, David
Setter, Drew
Idsinga, Beverly
Arencon, Diego
Seligman, Deborah
Horan, Thomas
Minzner, Richard
Jones, La Vanda
Gonzales, Ricardo
Gonzales, Ricardo
McGonagle, Minda
Weaks , Dan
Weaks , Dan
Shoats, Marlene (Marla)
Weaks , Dan
Moellenberg, Dalva
Koob, Julianna
Park, Alfred
Saavedra, Marc
Bowen, Michael
Ryan, John
Martinez, Eric
Riley , Zachary
Thompson, Jason

In [23]:
import pandas as pd
import numpy as np

#import the csv using pandas; convert the currency to general first
events = pd.read_csv('events.csv', names =['page_id', 'lob_name', 'date_occurred', 'event', "blank", 'amount'])
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2236 entries, 0 to 2235
Data columns (total 6 columns):
page_id          2236 non-null int64
lob_name         2236 non-null object
date_occurred    2236 non-null object
event            2236 non-null object
blank            0 non-null float64
amount           2236 non-null object
dtypes: float64(1), int64(1), object(4)
memory usage: 104.9+ KB

In [24]:
events

,page_id,lob_name,date_occurred,event,blank,amount
0,5827,"Walker , Jerry",1/17/2017,2017 Legislative Reception & Dinner,NaN,$500.00
1,5827,"Walker , Jerry",1/19/2017,2017 Democrat Legislative Reception & Dinner,NaN,$500.00
2,5944,"Killen, Patrick",1/26/2017,Dinner,NaN,$500.00
3,5998,"Christopher, John",1/30/2017,Legislative Dinner,NaN,"$10,340.67"
4,6009,"Ning, Natasha",1/31/2017,Reception,NaN,"$4,248.40"
5,6014,"Jones, La Vanda",2/3/2017,Luncheon,NaN,"$1,252.70"
6,6020,"D'Antonio , Michael",2/8/2017,NM Oil & Gas Association Board of Directors Di...,NaN,"$13,145.41"
7,6022,"D'Antonio , Michael",2/8/2017,NM Oil & Gas Association Board of Directors Di...,NaN,"$15,711.59"
8,6029,"Walker , Jerry",2/14/2017,Hispanic Culture Day Luncheon,NaN,$500.00
9,6030,"Bowen, Michael",2/15/2017,Legislative Reception & Dinner,NaN,"$15,844.85"
10,6034,"Moore, Brian",2/24/2017,Committee Meal,NaN,$507.39
11,6035,"Ning, Natasha",2/22/2017,ARS reception,NaN,"$5,666.67"
12,6037,"Duran, Mark",2/27/2017,Dinner,NaN,"$4,469.74"
13,6039,"Young, Tasia",3/7/2017,Meal Expense,NaN,$730.40
14,6051,"Duran, Mark",3/17/2017,End of Session Dinner,NaN,$891.32
15,6086,"Thompson, Jr. , John",1/30/2017,Dinner,NaN,$337.92
16,6086,"Thompson, Jr. , John",2/3/2017,South Valley Day Lunch / Pizza,NaN,$160.98
17,6086,"Thompson, Jr. , John",2/8/2017,Dinner,NaN,$145.90
18,6086,"Thompson, Jr. , John",2/9/2017,Dinner,NaN,$217.20
19,6086,"Thompson, Jr. , John",2/10/2017,Dinner,NaN,$233.50
20,6086,"Thompson, Jr. , John",2/20/2017,Dinner,NaN,$225.77
21,6086,"Thompson, Jr. , John",2/20/2017,Dinner,NaN,$251.94
22,6086,"Thompson, Jr. , John",2/21/2017,Dinner,NaN,$247.82
23,6086,"Thompson, Jr. , John",2/27/2017,Dinner,NaN,$120.00
24,6086,"Thompson, Jr. , John",2/27/2017,Dinner,NaN,$135.28
25,6086,"Thompson, Jr. , John",2/27/2017,Lunch at Capitol,NaN,$150.00
26,6086,"Thompson, Jr. , John",2/28/2017,Dinner,NaN,$130.00
27,6100,"Martinez, Katherine",1/24/2017,Legislative Dinner,NaN,"$3,500.00"
28,6105,"Balzano, Cristoforo",1/26/2017,Lunch,NaN,$211.45
29,6105,"Balzano, Cristoforo",1/27/2017,Committee Breakfast,NaN,$136.71
...,...,...,...,...,...,...
2206,6426,"Weaks , Dan",1/16/2017,Republican Party Legislative Reception,NaN,$400.00
2207,6426,"Weaks , Dan",1/18/2017,Democratic Party of NM Dinner-Dup to Marla Shoats,NaN,$400.00
2208,6430,"Moellenberg, Dalva",2/9/2017,Sponsorship of HEN RC dinner,NaN,$286.60
2209,6439,"Koob, Julianna",1/30/2017,House Chairpersons breakfast,NaN,$400.00
2210,6439,"Koob, Julianna",2/6/2017,House Judiciary Member & staff,NaN,$467.34
2211,6439,"Koob, Julianna",2/9/2017,committee dinner,NaN,$217.19
2212,6439,"Koob, Julianna",2/10/2017,CPAC committee dinner,NaN,$143.60
2213,6439,"Koob, Julianna",2/10/2017,Senate Judiciary Committee,NaN,$249.85
2214,6439,"Koob, Julianna",2/16/2017,100th bill party,NaN,$250.00
2215,6439,"Koob, Julianna",2/16/2017,Committee dinner,NaN,$270.69
2216,6439,"Koob, Julianna",2/21/2017,Health committee dinner,NaN,$200.00
2217,6439,"Koob, Julianna",2/21/2017,B&I committee dinner,NaN,$225.78
2218,6457,"Park, Alfred",1/26/2017,House Democratic Cuaucs Dinner,NaN,$337.92
2219,6457,"Park, Alfred",2/2/2017,Legislative Committee Dinner,NaN,$250.00
2220,6457,"Park, Alfred",2/15/2017,100 Bill Party,NaN,$250.00
2221,6478,"Saavedra, Marc",2/17/2017,House Education Dinner,NaN,$100.00
2222,6478,"Saavedra, Marc",3/9/2017,Senate Rulkes Committee Breakfast,NaN,$70.00
2223,6485,"Bowen, Michael",2/22/2017,Dinner Powdrell's BBQ Partial Sponsorship,NaN,$150.00
2224,6485,"Bowen, Michael",2/23/2017,Dinner NMACC Partial Sponsorship,NaN,$100.00
2225,6485,"Bowen, Michael",2/27/2017,Dinner Senate Ed. Com. Partial Sponsorship,NaN,$130.00
2226,6506,"Ryan, John",3/10/2017,Dinner,NaN,$127.00
2227,6516,"Martinez, Eric",3/14/2017,Senator Richard Martinez Birthday,NaN,$600.00
2228,6591,"Riley , Zachary",2/17/2017,Committee Dinner,NaN,$251.00
2229,6609,"Thompson, Jason",2/1/2017,Lunch delivery for Sen. Papen & Staff,NaN,$104.35
2230,6609,"Thompson, Jason",2/6/2017,House Labor & ED Committee Dinner,NaN,$145.90
2231,6609,"Thompson, Jason",2/16/2017,House Business & Industry Committee Dinner,NaN,$225.78
2232,6609,"Thompson, Jason",2/22/2017,Dinner for House Members,NaN,$120.00
2233,6609,"Thompson, Jason",2/27/2017,House Majority Staff Dinner,NaN,$234.46
2234,6609,"Thompson, Jason",2/27/2017,Pistacios for legislators & staff,NaN,$253.29
2235,6609,"Thompson, Jason",2/28/2017,House Indian Affairs Committee Dinner,NaN,$150.00

In [25]:
#convert to csv and convert dollar amounts, check for duplicates
events.to_csv('eventsm170514.csv')

In [16]:
eventsm17 = pd.read_csv('eventsm170514.csv')
eventsm17.head()

,Unnamed: 0,page_id,lob_name,date_occurred,event,blank,amount
0,0,5827,"Walker , Jerry",1/17/17,2017 Legislative Reception & Dinner,NaN,500.00
1,1,5827,"Walker , Jerry",1/19/17,2017 Democrat Legislative Reception & Dinner,NaN,500.00
2,2,5944,"Killen, Patrick",1/26/17,Dinner,NaN,500.00
3,3,5998,"Christopher, John",1/30/17,Legislative Dinner,NaN,10340.67
4,4,6009,"Ning, Natasha",1/31/17,Reception,NaN,4248.40

In [17]:
eventsm17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 7 columns):
Unnamed: 0       267 non-null int64
page_id          267 non-null int64
lob_name         267 non-null object
date_occurred    267 non-null object
event            267 non-null object
blank            0 non-null float64
amount           267 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 14.7+ KB

In [18]:
eventsm17.amount.sum()

138063.13

In [19]:
eventsm17.to_csv('20170513events.csv')